# Generated by Django 4.0.2 on 2022-03-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
