# Generated by Django 4.0.2 on 2022-03-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_question_short_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='short_date',
        ),
    ]
